name: zefyr_toolbar
description: It's a fork from https://github.com/memspace/zefyr
version: 0.10.1-dev.0
homepage: https://github.com/harshlohia/zefyr
publish_to: https://pub.dev/publishers/packs.apexteam.net

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^5.0.0
  quill_delta: ^1.0.0
  notus: ^0.1.0
  meta: ^1.1.0
  quiver_hashcode: ^2.0.0
  clipboard_manager: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
